version: "3.8"

services:
  storage:
    build: .
    volumes:
      - ./storage:/storage/storage
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    ports:
      - 5432:5432

  kubo-ipfs:
    image: ipfs/kubo:v0.15.0
