version: "3.8"

services:
  storage:
    build: .
    env_file: .env.local
    volumes:
      - ./storage:/storage/storage
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgres:
    ports:
      - 5432:5432

  kubo:
    image: ipfs/kubo:v0.15.0
    ports:
      - 5001:5001

  custody:
    image: ghcr.io/merklebot/custody:main
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}/custody
      - CRUST_MNEMONIC=
      - IPFS_ADDRESS=/dns4/kubo/tcp/5001
    ports:
      - 8001:8000
