version: "3.8"

services:
  storage:
    build: .
    volumes:
      - ./storage:/storage/storage
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  postgres:
    ports:
      - 5432:5432

  kubo:
    image: ipfs/kubo:v0.15.0
    ports:
      - 5001:5001

  custody:
    image: ghcr.io/merklebot/custody:main
    env_file: .env
    ports:
      - 8001:8000
