version: "3.8"

services:
  storage:
    command:
      - "/storage/start.sh"

#  postgres:
#    image: postgres:15
#    environment:
#      - POSTGRES_SERVER
#      - POSTGRES_USER
#      - POSTGRES_PASSWORD
#      - POSTGRES_DB
