version: "3.8"

services:
  storage:
    image: ghcr.io/merklebot/storage:main
    env_file: .env.prod
    networks:
      bridge:
      internal:
        # One alias per tenant is required for custody to storage callbacks unless wildcard subdomain support is not released.
        # https://github.com/moby/moby/pull/43444
        aliases:
          - "dev.${DOCKER_SWARM_STACK_NAME}_storage"
          - "droneselfie.${DOCKER_SWARM_STACK_NAME}_storage"

    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.storage.entrypoints=websecure
        - traefik.http.routers.storage.rule=Host(`storage.api2.merklebot.com`) || HostRegexp(`{tenant:[\w-]+}.storage.api2.merklebot.com`)
        - traefik.http.routers.storage.tls=true
        - traefik.http.routers.storage.tls.certresolver=letsencrypt-dnschallenge
        - traefik.http.routers.storage.tls.domains[0].main=storage.api2.merklebot.com
        - traefik.http.routers.storage.tls.domains[0].sans=*.storage.api2.merklebot.com
        - traefik.http.routers.storage.service=storage
        - traefik.http.services.storage.loadbalancer.server.port=${SERVER_PORT}
        # - traefik.http.middlewares.strip-storage.stripprefix.prefixes=${SERVER_ROOT_PATH}
        # - traefik.http.routers.storage.middlewares=strip-storage@docker

  postgres:
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.labels.postgres == true

volumes:
  postgres:
    external: true

networks:
  internal:
    external: true # externally created
  bridge:
    external: true
