"""User model

Revision ID: c6632fd5e42e
Revises: 0903d9db4e1b
Create Date: 2022-11-04 13:59:54.089853

"""
import sqlalchemy as sa
from alembic import op

from storage.db.multitenancy import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "c6632fd5e42e"
down_revision = "0903d9db4e1b"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema=schema)
    # ### end Alembic commands ###
