"""Access token for users

Revision ID: 7a2d90c8f7cc
Revises: c6632fd5e42e
Create Date: 2022-11-09 17:18:15.712028

"""
import sqlalchemy as sa
from alembic import op

from storage.db.multitenancy import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "7a2d90c8f7cc"
down_revision = "c6632fd5e42e"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_token", sa.String(length=64), nullable=False),
        sa.Column("expiry", sa.TIMESTAMP(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            [f"{schema}.users.id"],
            name=op.f("fk_tokens_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens")),
        schema=schema,
    )
    op.create_index(
        op.f("ix_tokens_expiry"),
        "tokens",
        ["expiry"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_tokens_hashed_token"),
        "tokens",
        ["hashed_token"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f("ix_tokens_id"),
        "tokens",
        ["id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_tokens_id"),
        table_name="tokens",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_tokens_hashed_token"),
        table_name="tokens",
        schema=schema,
    )
    op.drop_index(
        op.f("ix_tokens_expiry"),
        table_name="tokens",
        schema=schema,
    )
    op.drop_table("tokens", schema=schema)
    # ### end Alembic commands ###
