"""Remove dummy model

Revision ID: 0903d9db4e1b
Revises: 9fa9c8a9ae35
Create Date: 2022-11-04 12:45:44.183165

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0903d9db4e1b"
down_revision = "9fa9c8a9ae35"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tenants_id", table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="tenants_pkey"),
    )
    op.create_index("ix_tenants_id", "tenants", ["id"], unique=False)
    # ### end Alembic commands ###
