"""Content model

Revision ID: 848a67166f63
Revises: 7a2d90c8f7cc
Create Date: 2022-11-11 20:07:08.971581

"""
import sqlalchemy as sa
import sqlalchemy_utils as sa_utils
from alembic import op

from storage.db.multitenancy import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "848a67166f63"
down_revision = "7a2d90c8f7cc"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ipfs_cid", sa.String(length=265), nullable=True),
        sa.Column("origin", sa_utils.types.URLType(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            [f"{schema}.users.id"],
            name=op.f("fk_contents_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contents")),
        schema=schema,
    )
    op.create_index(
        op.f("ix_contents_id"),
        "contents",
        ["id"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_contents_id"),
        table_name="contents",
        schema=schema,
    )
    op.drop_table("contents", schema=schema)
    # ### end Alembic commands ###
