"""key model

Revision ID: 738f87e4a996
Revises: 5d89b8f31a7d
Create Date: 2022-12-02 13:29:08.559549

"""
import sqlalchemy as sa
from alembic import op

from storage.db.multitenancy import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "738f87e4a996"
down_revision = "5d89b8f31a7d"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aes_key", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            [f"{schema}.users.id"],
            name=op.f("fk_keys_owner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_keys")),
        schema=schema,
    )
    op.create_index(op.f("ix_keys_id"), "keys", ["id"], unique=False, schema=schema)


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_keys_id"), table_name="keys", schema=schema)
    op.drop_table("keys", schema=schema)
    # ### end Alembic commands ###
