"""Job model

Revision ID: 51a5feebcdc7
Revises: 738f87e4a996
Create Date: 2022-12-14 17:18:21.541279

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from storage.db.multitenancy import for_each_tenant_schema

# revision identifiers, used by Alembic.
revision = "51a5feebcdc7"
down_revision = "738f87e4a996"
branch_labels = None
depends_on = None


@for_each_tenant_schema
def upgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("ENCRYPT", "DECRYPT", "REPLICATE", "RESTORE", name="jobkind"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "ACCEPTED",
                "REJECTED",
                "INPROGRESS",
                "CANCELLED",
                "FAILED",
                "COMPLETE",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_id"],
            [f"{schema}.contents.id"],
            name=op.f("fk_jobs_content_id_contents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_jobs_content_id"),
        "jobs",
        ["content_id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_jobs_id"),
        "jobs",
        ["id"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_jobs_kind"),
        "jobs",
        ["kind"],
        unique=False,
        schema=schema,
    )
    op.create_index(
        op.f(f"ix_{schema}_jobs_status"),
        "jobs",
        ["status"],
        unique=False,
        schema=schema,
    )
    # ### end Alembic commands ###


@for_each_tenant_schema
def downgrade(schema: str):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(f"ix_{schema}_jobs_status"),
        table_name="jobs",
        schema=schema,
    )
    op.drop_index(op.f(f"ix_{schema}_jobs_kind"), table_name="jobs", schema=schema)
    op.drop_index(op.f(f"ix_{schema}_jobs_id"), table_name="jobs", schema=schema)
    op.drop_index(
        op.f(f"ix_{schema}_jobs_content_id"),
        table_name="jobs",
        schema=schema,
    )
    op.drop_table("jobs", schema=schema)
    # ### end Alembic commands ###
